services:
    ui:
      build: 
        context: ./dashboard
        dockerfile: Dockerfile
      container_name: dashboard
      ports:
        - "9000:3000"

    mongodb:
      ports:
           - '9003:27017'
      container_name: mongo_container
      restart: always
      logging:
          options:
              max-size: 1g
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
      image: mongo
      volumes:
            - ./data:/data/db